import pandas as pd
import os
import time
import random
import requests
import io
import yfinance as yf
import pandas_ta as ta
import numpy as np
from tqdm import tqdm

# --- PART 1: THE DOWNLOADER FUNCTION ---
def get_quant_data(ticker_symbol):
    """Downloads a single stock and calculates indicators"""
    try:
        # UPDATED: Fixed start date to capture 2019-2025 (COVID crash included)
        # threads=False prevents yfinance from freezing in long loops
        stock = yf.download(f'{ticker_symbol}.NS', start="2019-01-01", progress=False, threads=False)
        
        if len(stock) == 0: return None

        # Fix for yfinance MultiIndex issue
        if isinstance(stock.columns, pd.MultiIndex):
            stock.columns = stock.columns.get_level_values(0)

        # Calculate Indicators
        # 1. Log Returns (The most important feature for AI)
        stock['Log_Ret'] = np.log(stock['Close'] / stock['Close'].shift(1))
        
        # 2. RSI (Relative Strength Index)
        stock['RSI'] = ta.rsi(stock['Close'], length=14)
        
        # 3. EMA (Trend)
        stock['EMA_50'] = ta.ema(stock['Close'], length=50)

        # Drop NaN values generated by indicators
        stock.dropna(inplace=True)
        return stock
    except Exception as e:
        return None

# --- PART 2: THE MASTER LIST FETCHER ---
def get_nse_master_list():
    """Fetches the official list of active NSE stocks"""
    print("--- Connecting to NSE Server... ---")
    
    url = "https://nsearchives.nseindia.com/content/equities/EQUITY_L.csv"
    
    # Use 'Session' to mimic a real browser so NSE doesn't block us
    session = requests.Session()
    session.headers.update({
        "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36",
        "Accept": "*/*"
    })
    
    try:
        response = session.get(url, timeout=10)
        
        # Check for "Access Denied" HTML response
        if b"<!DOCTYPE html>" in response.content:
            print("Error: NSE blocked the request.")
            return []

        csv_data = io.StringIO(response.content.decode('utf-8'))
        master_df = pd.read_csv(csv_data)
        
        # CRITICAL FIX: Clean column names (Remove spaces like ' SERIES')
        master_df.columns = master_df.columns.str.strip()
        
        # Filter: Equity (EQ) and Book Entry (BE) only
        equity_df = master_df[master_df['SERIES'].isin(['EQ', 'BE'])]
        tickers = equity_df['SYMBOL'].unique().tolist()
        
        print(f"Success! Found {len(tickers)} active stocks.")
        return tickers
        
    except Exception as e:
        print(f"Error fetching list: {e}")
        # Fallback list if NSE server fails
        return ["RELIANCE", "TCS", "HDFCBANK", "INFY", "ICICIBANK", "SBIN"]

# --- PART 3: THE MAIN LOOP ---
if __name__ == "__main__":
    tickers = get_nse_master_list()
    
    if not tickers:
        print("No stocks found. Exiting.")
        exit()
    
    save_dir = "lake/silver"
    os.makedirs(save_dir, exist_ok=True)
    
    print(f"\n--- 🚀 STARTING DOWNLOAD (2019 - Present) ---")
    print(f" Saving to: {os.path.abspath(save_dir)}")
    print("⚠️  Press Ctrl+C to stop. Script will resume automatically next time.")

    for ticker in tqdm(tickers):
        save_path = f"{save_dir}/{ticker}_processed.csv"
        
        # Resume Logic: Skip if file already exists
        if os.path.exists(save_path):
            continue
            
        df = get_quant_data(ticker)
        
        if df is not None and not df.empty:
            df.to_csv(save_path)
        
        # Sleep to avoid IP Ban
        time.sleep(random.uniform(0.5, 1.5))